### ISSUE TITLE
Null reference when using nudge command

### ISSUE THREAD

**Issue by davidfowl** [JabbR/JabbR#28]
Happens if the user doesn't exist.

From elmah:

```
System.NullReferenceException
Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at SignalR.Samples.Hubs.Chat.Chat.HandleNudge(ChatUser user, String[] parts) in d:\temp\1igq1dri.34a\input\Chat\Chat.cs:line 456
   at SignalR.Samples.Hubs.Chat.Chat.TryHandleCommand(String command) in d:\temp\1igq1dri.34a\input\Chat\Chat.cs:line 258
   at SignalR.Samples.Hubs.Chat.Chat.Send(String content) in d:\temp\1igq1dri.34a\input\Chat\Chat.cs:line 86
```

**Comment by DamianEdwards** [comment]
fixed
