### ISSUE TITLE
Content Providers don't show on refresh

### ISSUE THREAD

**Issue by WilliamBZA** [JabbR/JabbR#610]
It appears that content providers don't render the embedded HTML after a page refresh and the content is merely displayed as a link.

Steps to repro:
1. Go to #test
2. Paste a link to an image
3. The image should be displayed as embedded content correctly
4. Refresh the page
5. The image will now just be a link rather than an embedded image

**Comment by dpatti** [comment]
In trying to resolve this issue, I've tracked it down to an exception in `AppendMessage`. So the extra content is sent to the clients but never written to the database. The exception is as follows (disregard line numbers):

```
The operation cannot be completed because the DbContext has been disposed
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at JabbR.Models.PersistedRepository.GetMessagesById(String id) in c:\Users\Doug\dev\jabbr\JabbR\Models\PersistedRepository.cs:line 92
   at JabbR.Services.ChatService.AppendMessage(String id, String content) in c:\Users\Doug\dev\jabbr\JabbR\Services\ChatService.cs:line 519
   at JabbR.Chat.<>c__DisplayClass3b.<ProcessUrls>b__3a(Task`1[] tasks) in c:\Users\Doug\dev\jabbr\JabbR\Hubs\Chat.cs:line 536"
```

I believe the issue has something to do with the fact that content providers are evaluated asynchronously. I was able to resolve it by removing the `Dispose` definition in `Chat`. I am not confident that this is a good solution, but it does seem to work.

**Comment by davidfowl** [comment]
Yep. It's hacky and I need a better solution for this but we need to move all content providers to the client.
