### ISSUE TITLE
when user logged out i want to display msg to his friends

### ISSUE THREAD

**Issue by bangar** [JabbR/JabbR#824]
when user logged out i want to display msg to his friends so when i am using clients .client('friendconnectionid').broadcastloggedoutmsg(a,b)

i m receiving this error

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNet.SignalR.Hubs.SignalProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Object& , Object& )
   at CallSite.Target(Closure , CallSite , Object , Object& , Object& )
   at Invoker(CallSiteBinder , Object , Object[] )
   at Microsoft.VisualBasic.CompilerServices.IDOUtils.CreateRefCallSiteAndInvoke(CallSiteBinder Action, Object Instance, Object[] Arguments)
   at Microsoft.VisualBasic.CompilerServices.IDOBinder.IDOCall(IDynamicMetaObjectProvider Instance, String MemberName, Object[] Arguments, String[] ArgumentNames, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Wall.UserLoggedOff(Int64 LoggedOutUserId) in E:\wall4.5\App_Code\Wall.vb:line 181

Any solution ??

**Comment by davidfowl** [comment]
Wrong repository
